# Generated by Django 4.2 on 2023-04-23 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=45)),
                ('tipo', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('fecha_v', models.DateField()),
                ('tipo_pro', models.IntegerField()),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.persona')),
            ],
            options={
                'db_table': 'Ventas',
                'unique_together': {('id_venta', 'persona')},
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('raza', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=45)),
                ('peso', models.FloatField()),
                ('fecha_nac', models.DateField()),
                ('estado_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.persona')),
            ],
            options={
                'db_table': 'mascota',
                'unique_together': {('id_mascota', 'persona')},
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.venta')),
            ],
            options={
                'db_table': 'Ventas_has_Productos',
                'unique_together': {('venta', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id_consulta_medica', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_con', models.DateField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.mascota')),
            ],
            options={
                'db_table': 'Consulta_Medica',
                'unique_together': {('id_consulta_medica', 'mascota')},
            },
        ),
    ]
