# Generated by Django 4.2 on 2023-04-30 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='nombre',
            new_name='nombre_Mascota',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='nombre_Persona',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='nombre_pro',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fecha',
            new_name='fecha_ven',
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.persona'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.persona'),
        ),
    ]
