# Generated by Django 4.2 on 2023-05-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_nombre_mascota_nombre_mascota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.persona'),
        ),
    ]
